apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app: kris-service-71
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kris-service-71
  template:
    metadata:
      labels:
        app: kris-service-71
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.targetPort }}"
        prometheus.io/path: "/q/metrics"
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      containers:
      - name: kris-service-71
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /q/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /q/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
